"""add_audio_production_tables

Revision ID: 3a3b3d2fc44c
Revises: 52a86866b0ba
Create Date: 2025-12-19 09:18:55.613072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a3b3d2fc44c'
down_revision: Union[str, None] = '52a86866b0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_segment_metadata',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.String(length=255), nullable=False),
    sa.Column('segment_id', sa.String(length=255), nullable=False),
    sa.Column('processing_chain', sa.JSON(), nullable=True),
    sa.Column('needs_revision', sa.Boolean(), nullable=False),
    sa.Column('revision_notes', sa.Text(), nullable=True),
    sa.Column('raw_audio_cache_key', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_segment_metadata_project_chapter', 'audio_segment_metadata', ['project_id', 'chapter_id'], unique=False)
    op.create_index('idx_segment_metadata_unique', 'audio_segment_metadata', ['project_id', 'chapter_id', 'segment_id'], unique=True)
    op.create_index(op.f('ix_audio_segment_metadata_chapter_id'), 'audio_segment_metadata', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_audio_segment_metadata_project_id'), 'audio_segment_metadata', ['project_id'], unique=False)
    op.create_index(op.f('ix_audio_segment_metadata_segment_id'), 'audio_segment_metadata', ['segment_id'], unique=False)
    op.create_table('sfx_segments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('blob_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sfx_chapter_order', 'sfx_segments', ['chapter_id', 'display_order'], unique=False)
    op.create_index('idx_sfx_project_chapter', 'sfx_segments', ['project_id', 'chapter_id', 'display_order'], unique=False)
    op.create_index(op.f('ix_sfx_segments_chapter_id'), 'sfx_segments', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_sfx_segments_project_id'), 'sfx_segments', ['project_id'], unique=False)
    op.alter_column('audio_cache', 'voice_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audio_cache', 'hit_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_audio_cache_expires_at'), table_name='audio_cache')
    op.drop_index(op.f('ix_audio_cache_last_accessed_at'), table_name='audio_cache')
    op.create_index('idx_audio_cache_expires', 'audio_cache', ['expires_at'], unique=False)
    op.create_index('idx_audio_cache_key', 'audio_cache', ['cache_key'], unique=False)
    op.create_index('idx_audio_cache_last_accessed', 'audio_cache', ['last_accessed_at'], unique=False)
    op.create_index('idx_audio_cache_tenant', 'audio_cache', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audio_cache_tenant', table_name='audio_cache')
    op.drop_index('idx_audio_cache_last_accessed', table_name='audio_cache')
    op.drop_index('idx_audio_cache_key', table_name='audio_cache')
    op.drop_index('idx_audio_cache_expires', table_name='audio_cache')
    op.create_index(op.f('ix_audio_cache_last_accessed_at'), 'audio_cache', ['last_accessed_at'], unique=False)
    op.create_index(op.f('ix_audio_cache_expires_at'), 'audio_cache', ['expires_at'], unique=False)
    op.alter_column('audio_cache', 'hit_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('audio_cache', 'voice_settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_sfx_segments_project_id'), table_name='sfx_segments')
    op.drop_index(op.f('ix_sfx_segments_chapter_id'), table_name='sfx_segments')
    op.drop_index('idx_sfx_project_chapter', table_name='sfx_segments')
    op.drop_index('idx_sfx_chapter_order', table_name='sfx_segments')
    op.drop_table('sfx_segments')
    op.drop_index(op.f('ix_audio_segment_metadata_segment_id'), table_name='audio_segment_metadata')
    op.drop_index(op.f('ix_audio_segment_metadata_project_id'), table_name='audio_segment_metadata')
    op.drop_index(op.f('ix_audio_segment_metadata_chapter_id'), table_name='audio_segment_metadata')
    op.drop_index('idx_segment_metadata_unique', table_name='audio_segment_metadata')
    op.drop_index('idx_segment_metadata_project_chapter', table_name='audio_segment_metadata')
    op.drop_table('audio_segment_metadata')
    # ### end Alembic commands ###
