"""add_action_history_table

Revision ID: a922f38873df
Revises: b1da7da88de8
Create Date: 2025-12-16 16:19:48.492821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a922f38873df'
down_revision: Union[str, None] = 'b1da7da88de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_description', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_undone', sa.Boolean(), nullable=False),
    sa.Column('undone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_history_created_at'), 'action_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_action_history_project_id'), 'action_history', ['project_id'], unique=False)
    op.create_index(op.f('ix_action_history_tenant_id'), 'action_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_action_history_user_id'), 'action_history', ['user_id'], unique=False)
    op.alter_column('chapter_plans', 'is_complete',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_chapter_plans_chapter_id'), table_name='chapter_plans')
    op.drop_index(op.f('ix_chapter_plans_project_id'), table_name='chapter_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chapter_plans_project_id'), 'chapter_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_chapter_plans_chapter_id'), 'chapter_plans', ['chapter_id'], unique=False)
    op.alter_column('chapter_plans', 'is_complete',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_action_history_user_id'), table_name='action_history')
    op.drop_index(op.f('ix_action_history_tenant_id'), table_name='action_history')
    op.drop_index(op.f('ix_action_history_project_id'), table_name='action_history')
    op.drop_index(op.f('ix_action_history_created_at'), table_name='action_history')
    op.drop_table('action_history')
    # ### end Alembic commands ###
