"""Add preset_id to audio_segment_metadata

Revision ID: dada0ab8db9a
Revises: 3a3b3d2fc44c
Create Date: 2025-12-19 18:06:46.105576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dada0ab8db9a'
down_revision: Union[str, None] = '3a3b3d2fc44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_segment_metadata', sa.Column('preset_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_segment_metadata', 'preset_id')
    # ### end Alembic commands ###
