/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdVoiceRouteImport } from './routes/projects.$projectId.voice'
import { Route as ProjectsProjectIdPropertiesRouteImport } from './routes/projects.$projectId.properties'
import { Route as ProjectsProjectIdPlanningRouteImport } from './routes/projects.$projectId.planning'
import { Route as ProjectsProjectIdManuscriptRouteImport } from './routes/projects.$projectId.manuscript'
import { Route as ProjectsProjectIdExportRouteImport } from './routes/projects.$projectId.export'
import { Route as ProjectsProjectIdEditRouteImport } from './routes/projects.$projectId.edit'
import { Route as ProjectsProjectIdCharactersRouteImport } from './routes/projects.$projectId.characters'
import { Route as ProjectsProjectIdCastingRouteImport } from './routes/projects.$projectId.casting'
import { Route as ProjectsProjectIdBookRouteImport } from './routes/projects.$projectId.book'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdVoiceRoute = ProjectsProjectIdVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdPropertiesRoute =
  ProjectsProjectIdPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPlanningRoute =
  ProjectsProjectIdPlanningRouteImport.update({
    id: '/planning',
    path: '/planning',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdManuscriptRoute =
  ProjectsProjectIdManuscriptRouteImport.update({
    id: '/manuscript',
    path: '/manuscript',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdExportRoute = ProjectsProjectIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdEditRoute = ProjectsProjectIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdCharactersRoute =
  ProjectsProjectIdCharactersRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCastingRoute =
  ProjectsProjectIdCastingRouteImport.update({
    id: '/casting',
    path: '/casting',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdBookRoute = ProjectsProjectIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/book': typeof ProjectsProjectIdBookRoute
  '/projects/$projectId/casting': typeof ProjectsProjectIdCastingRoute
  '/projects/$projectId/characters': typeof ProjectsProjectIdCharactersRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/manuscript': typeof ProjectsProjectIdManuscriptRoute
  '/projects/$projectId/planning': typeof ProjectsProjectIdPlanningRoute
  '/projects/$projectId/properties': typeof ProjectsProjectIdPropertiesRoute
  '/projects/$projectId/voice': typeof ProjectsProjectIdVoiceRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/book': typeof ProjectsProjectIdBookRoute
  '/projects/$projectId/casting': typeof ProjectsProjectIdCastingRoute
  '/projects/$projectId/characters': typeof ProjectsProjectIdCharactersRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/manuscript': typeof ProjectsProjectIdManuscriptRoute
  '/projects/$projectId/planning': typeof ProjectsProjectIdPlanningRoute
  '/projects/$projectId/properties': typeof ProjectsProjectIdPropertiesRoute
  '/projects/$projectId/voice': typeof ProjectsProjectIdVoiceRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/book': typeof ProjectsProjectIdBookRoute
  '/projects/$projectId/casting': typeof ProjectsProjectIdCastingRoute
  '/projects/$projectId/characters': typeof ProjectsProjectIdCharactersRoute
  '/projects/$projectId/edit': typeof ProjectsProjectIdEditRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/manuscript': typeof ProjectsProjectIdManuscriptRoute
  '/projects/$projectId/planning': typeof ProjectsProjectIdPlanningRoute
  '/projects/$projectId/properties': typeof ProjectsProjectIdPropertiesRoute
  '/projects/$projectId/voice': typeof ProjectsProjectIdVoiceRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/book'
    | '/projects/$projectId/casting'
    | '/projects/$projectId/characters'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/export'
    | '/projects/$projectId/manuscript'
    | '/projects/$projectId/planning'
    | '/projects/$projectId/properties'
    | '/projects/$projectId/voice'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/projects'
    | '/projects/$projectId/book'
    | '/projects/$projectId/casting'
    | '/projects/$projectId/characters'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/export'
    | '/projects/$projectId/manuscript'
    | '/projects/$projectId/planning'
    | '/projects/$projectId/properties'
    | '/projects/$projectId/voice'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/book'
    | '/projects/$projectId/casting'
    | '/projects/$projectId/characters'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/export'
    | '/projects/$projectId/manuscript'
    | '/projects/$projectId/planning'
    | '/projects/$projectId/properties'
    | '/projects/$projectId/voice'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/voice': {
      id: '/projects/$projectId/voice'
      path: '/voice'
      fullPath: '/projects/$projectId/voice'
      preLoaderRoute: typeof ProjectsProjectIdVoiceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/properties': {
      id: '/projects/$projectId/properties'
      path: '/properties'
      fullPath: '/projects/$projectId/properties'
      preLoaderRoute: typeof ProjectsProjectIdPropertiesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/planning': {
      id: '/projects/$projectId/planning'
      path: '/planning'
      fullPath: '/projects/$projectId/planning'
      preLoaderRoute: typeof ProjectsProjectIdPlanningRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/manuscript': {
      id: '/projects/$projectId/manuscript'
      path: '/manuscript'
      fullPath: '/projects/$projectId/manuscript'
      preLoaderRoute: typeof ProjectsProjectIdManuscriptRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/export': {
      id: '/projects/$projectId/export'
      path: '/export'
      fullPath: '/projects/$projectId/export'
      preLoaderRoute: typeof ProjectsProjectIdExportRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/edit': {
      id: '/projects/$projectId/edit'
      path: '/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof ProjectsProjectIdEditRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/characters': {
      id: '/projects/$projectId/characters'
      path: '/characters'
      fullPath: '/projects/$projectId/characters'
      preLoaderRoute: typeof ProjectsProjectIdCharactersRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/casting': {
      id: '/projects/$projectId/casting'
      path: '/casting'
      fullPath: '/projects/$projectId/casting'
      preLoaderRoute: typeof ProjectsProjectIdCastingRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/book': {
      id: '/projects/$projectId/book'
      path: '/book'
      fullPath: '/projects/$projectId/book'
      preLoaderRoute: typeof ProjectsProjectIdBookRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBookRoute: typeof ProjectsProjectIdBookRoute
  ProjectsProjectIdCastingRoute: typeof ProjectsProjectIdCastingRoute
  ProjectsProjectIdCharactersRoute: typeof ProjectsProjectIdCharactersRoute
  ProjectsProjectIdEditRoute: typeof ProjectsProjectIdEditRoute
  ProjectsProjectIdExportRoute: typeof ProjectsProjectIdExportRoute
  ProjectsProjectIdManuscriptRoute: typeof ProjectsProjectIdManuscriptRoute
  ProjectsProjectIdPlanningRoute: typeof ProjectsProjectIdPlanningRoute
  ProjectsProjectIdPropertiesRoute: typeof ProjectsProjectIdPropertiesRoute
  ProjectsProjectIdVoiceRoute: typeof ProjectsProjectIdVoiceRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBookRoute: ProjectsProjectIdBookRoute,
  ProjectsProjectIdCastingRoute: ProjectsProjectIdCastingRoute,
  ProjectsProjectIdCharactersRoute: ProjectsProjectIdCharactersRoute,
  ProjectsProjectIdEditRoute: ProjectsProjectIdEditRoute,
  ProjectsProjectIdExportRoute: ProjectsProjectIdExportRoute,
  ProjectsProjectIdManuscriptRoute: ProjectsProjectIdManuscriptRoute,
  ProjectsProjectIdPlanningRoute: ProjectsProjectIdPlanningRoute,
  ProjectsProjectIdPropertiesRoute: ProjectsProjectIdPropertiesRoute,
  ProjectsProjectIdVoiceRoute: ProjectsProjectIdVoiceRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
